services:
  auth-server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.2.2}
    command: server
    restart: unless-stopped
    environment:
      AUTHENTIK_POSTGRESQL__HOST: auth-db
      AUTHENTIK_POSTGRESQL__PORT: ${AUTHENTIK_POSTGRESQL__PORT}
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRESQL__NAME}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRESQL__USER}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRESQL__PASSWORD}
      AUTHENTIK_POSTGRESQL__SSLMODE: verify-full
      AUTHENTIK_POSTGRESQL__SSLROOTCERT: /certs/ca.crt
      AUTHENTIK_POSTGRESQL__SSLCERT: /certs/client.crt
      AUTHENTIK_POSTGRESQL__SSLKEY: /certs/client.key
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_LISTEN__HTTPS: ${AUTHENTIK_LISTEN__HTTPS}
    volumes:
      - ./authentik/data:/data
      - ./authentik/custom-templates:/templates
      - ../../ca/cert/ca.crt:/certs/ca.crt:ro
      - ../cert/auth_server/client.crt:/certs/client.crt:ro
      - ../cert/auth_server/client.key:/certs/client.key:ro
    shm_size: 512mb
    networks:
      - authentik

  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.2.2}
    command: worker
    restart: unless-stopped
    user: root
    environment:
      AUTHENTIK_POSTGRESQL__HOST: auth-db
      AUTHENTIK_POSTGRESQL__PORT: ${AUTHENTIK_POSTGRESQL__PORT}
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRESQL__NAME}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRESQL__USER}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRESQL__PASSWORD}
      AUTHENTIK_POSTGRESQL__SSLMODE: verify-full
      AUTHENTIK_POSTGRESQL__SSLROOTCERT: /certs/ca.crt
      AUTHENTIK_POSTGRESQL__SSLCERT: /certs/client.crt
      AUTHENTIK_POSTGRESQL__SSLKEY: /certs/client.key
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_BOOTSTRAP_PASSWORD: ${AUTHENTIK_BOOTSTRAP_PASSWORD}
      AUTHENTIK_BOOTSTRAP_EMAIL: ${AUTHENTIK_BOOTSTRAP_EMAIL}
      AUTHENTIK_BOOTSTRAP_TOKEN: ${AUTHENTIK_BOOTSTRAP_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./authentik/data:/data
      - ./authentik/certs:/certs-extra
      - ./authentik/custom-templates:/templates
      - ../../ca/cert/ca.crt:/certs/ca.crt:ro
      - ../cert/auth_worker/client.crt:/certs/client.crt:ro
      - ../cert/auth_worker/client.key:/certs/client.key:ro
    shm_size: 512mb
    networks:
      - authentik
networks:
  authentik:
    external: true